### ISSUE TITLE
Handle the problem that is select arch, then 5.1/5.2 then another department

### ISSUE THREAD

**Issue by AfsanaBrishty** [Sajid576/AUSTJunction#38]

**Comment by Sajid576** [comment]
this problem is still not handled .!! 
select Arc ,then select 5.1 ,then select EEE/CSE , 5.1 is still selected in dropdown though the option is disabled in dropdown . And guess what I can go to next page by "NEXT" button . 

There can be 2 solutions.
1) when department dropdown is selected the semester dropdown will be reset .(5.1 & 5.2 will be disabled if Arch is not selected).

.
.
.
.
.
.
2) follow the 1st solution.. :3 :"V
